travis:
  secure:
    BINSTAR_TOKEN: RpiM+6ZS2GAOz1clMB3yVGxvvV828OE9mEG/VbaSCAdLK2vV7jwcv/RdplSYyflOVMxFc2ragkQxpGkWViycGAmt1iJs3eY7wW8Q0NlIhhvGQkhc8Rr2o0AoTCxFIvIWPea8Bs+aOiOZgLsOp5Lkh3qBwkmj1vuGYxs4cMllEW6lSdRrlsRBN3XdgxMZ544H9SU7If7ZLeiF6flPcHo6xu9Eu4TgvV90ZGmqMEW4Tldyb5Zy5wrZMPgO6tNxLUT3Pa9eXn74Utyj6zAyWNy7ey7maQgjiRyBdcXGmRYuziWDC9tuSv1ou50BVxPHdSKEhz4qJtlWGk+XQfrbxaNPhVsdGHAS66Hg0/E6BQ/rIgLSUPIbA+SrtJfpglEYH2Fk+Ao+JWFG6AbzJjFvyVQ2M2MGHxTTTeYlih12cQQJUr0tTYpOUN8W2SLNBUS9dP54Iqh7+f1E5K/kPQR02DtOSVglKBssV79Q6kxk40jI56ZjJ1aI6bUyEX5AFizHJ1j7FDO2Gs9mC0ztluB4zKBe04tSacxjIdJcpXsCCZOoQQ5qrqsDXIyBVWQ/26x2UP1hUdJSHyTEzq9nkKWDz90m1yF+YfIfCDOagSd+0WkTWE4kE5FxYx4RXpvq3l0I0N7/qTDlK5vWuOeLu2rQ1EsoIm5SFzFG38lmDPC91Z9BzdY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
